### ISSUE TITLE
Bring back iOS support

### ISSUE THREAD

**Issue by aginiewicz** [ajhager/libgdx-sbt-project.g8#80]
After fixing:
- https://github.com/ajhager/libgdx-sbt-project.g8/issues/78
- https://github.com/ajhager/libgdx-sbt-project.g8/issues/74
- https://github.com/ajhager/libgdx-sbt-project.g8/issues/73

in https://github.com/ajhager/libgdx-sbt-project.g8/pull/79 for Android and Desktop - I removed iOS due to some issues (see comments in pull request).

I'm opening this ticket to close above three and make statistics of open tickets look better :)

**Comment by johansja** [comment]
Just one note, the latest commit is causing some issue, which I think you should have noticed as well.

I can't get the iOS package downloaded from any of the repository, which is causing me some issue.

**Comment by ajhager** [comment]
I will take a look.

**Comment by ajhager** [comment]
I have published a new version of the ios plugin. Your plugins.sbt file should like this:

``` scala
resolvers += Resolver.url("scalasbt snapshots", new URL("http://repo.scala-sbt.org/scalasbt/sbt-pl    ugin-snapshots"))(Resolver.ivyStylePatterns)

addSbtPlugin("com.hanhuy.sbt" % "android-sdk-plugin" % "1.3.6")

addSbtPlugin("org.roboscala" % "sbt-robovm" % "1.0.0-alpha-04-SNAPSHOT")
```

I will do some more testing tomorrow, but I was able to get the basic example working.

**Comment by aginiewicz** [comment]
Soo... is there something left to do, or it works already? :) If it does, maybe we can close this one?

edit: I haven't tested on Windows - if this issue have been resolved, I think this one can be closed.

**Comment by giabao** [comment]
On Windows, run sbt in the generated project throw error:

```
[info] Loading project definition from C:\wd\tien-len\project
java.lang.UnsatisfiedLinkError: Native library for windows-x86_64 not found
        at org.robovm.llvm.NativeLibrary.load(NativeLibrary.java:75)
        at org.robovm.llvm.binding.LLVMJNI.<clinit>(LLVMJNI.java:741)
        at org.robovm.llvm.binding.LLVM.getLlvmHostTriple(LLVM.java:2833)
        at org.robovm.llvm.Target.<clinit>(Target.java:36)
        at org.robovm.compiler.config.Arch.getDefaultArch(Arch.java:60)
        at sbtrobovm.RobovmProjects$Standard$.robovmSettings$lzycompute(RobovmProjects.scala:253)
        at sbtrobovm.RobovmProjects$Standard$.robovmSettings(RobovmProjects.scala:196)
        at sbtrobovm.RobovmProjects$Standard$$anonfun$apply$39.apply(RobovmProjects.scala:282)
        at sbtrobovm.RobovmProjects$Standard$$anonfun$apply$39.apply(RobovmProjects.scala:282)
        at sbt.Project$ProjectDef.settings$lzycompute(Project.scala:225)
        at sbt.Project$ProjectDef.settings(Project.scala:225)
        at sbt.Project$class.copy$default$6(Project.scala:88)
        at sbt.Project$$anon$2.copy$default$6(Project.scala:274)
        at sbt.Project$$anonfun$dependsOn$4.apply(Project.scala:132)
        at sbt.Project$$anonfun$dependsOn$4.apply(Project.scala:132)
        at sbt.Project$ProjectDef.settings$lzycompute(Project.scala:225)
        at sbt.Project$ProjectDef.settings(Project.scala:225)
        at sbt.Project$class.copy$default$6(Project.scala:88)
        at sbt.Project$$anon$2.copy$default$6(Project.scala:274)
        at sbt.Load$$anonfun$resolveBase$1$$anonfun$apply$17.apply(Load.scala:383)
        at sbt.Load$$anonfun$resolveBase$1$$anonfun$apply$17.apply(Load.scala:383)
        at sbt.Project$ProjectDef.settings$lzycompute(Project.scala:225)
        at sbt.Project$ProjectDef.settings(Project.scala:225)
        at sbt.Load$.sbt$Load$$expandSettings$1(Load.scala:674)
        at sbt.Load$$anonfun$sbt$Load$$expandSettings$1$2.apply(Load.scala:680)
        at sbt.Load$$anonfun$sbt$Load$$expandSettings$1$2.apply(Load.scala:680)
        at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:51)
        at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:60)
        at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:34)
        at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:138)
        at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:105)
        at sbt.Load$.sbt$Load$$expandSettings$1(Load.scala:680)
        at sbt.Load$.resolveProject(Load.scala:682)
        at sbt.Load$.finalizeProject$1(Load.scala:549)
        at sbt.Load$.discoverAndLoad$1(Load.scala:562)
        at sbt.Load$.loadTransitive(Load.scala:570)
        at sbt.Load$.loadProjects$1(Load.scala:442)
        at sbt.Load$.loadUnit(Load.scala:446)
        at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
        at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
        at sbt.BuildLoader.apply(BuildLoader.scala:140)
        at sbt.Load$.loadAll(Load.scala:334)
        at sbt.Load$.loadURI(Load.scala:289)
        at sbt.Load$.load(Load.scala:285)
        at sbt.Load$.load(Load.scala:276)
        at sbt.Load$.apply(Load.scala:130)
        at sbt.Load$.defaultLoad(Load.scala:36)
        at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
        at sbt.Command$.process(Command.scala:92)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
        at sbt.State$$anon$1.process(State.scala:184)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.MainLoop$.next(MainLoop.scala:98)
        at sbt.MainLoop$.run(MainLoop.scala:91)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
        at sbt.Using.apply(Using.scala:24)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
        at sbt.MainLoop$.runLogged(MainLoop.scala:24)
        at sbt.StandardMain$.runManaged(Main.scala:53)
        at sbt.xMain.run(Main.scala:28)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:18)
        at xsbt.boot.Boot$.runImpl(Boot.scala:41)
        at xsbt.boot.Boot$.main(Boot.scala:17)
        at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.UnsatisfiedLinkError: Native library for windows-x86_64 not found
```

I must remove `LibgdxBuild.ios` from project/build.scala for sbt to work.

Question: Can we detect that g8 is running on Windows then automatically comment out ios related settings in project/build.scala?

**Comment by aginiewicz** [comment]
@ajhager the error above looks very different that what we seen before, have you maybe looked into it?

**Comment by Darkyenus** [comment]
iOS support is back in [my fork](https://github.com/Darkyenus/libgdx-sbt-project.g8).

**Comment by swolfekabaminc** [comment]
I noticed that the main repo is pointing to a version of robovm that no
longer resolves. Was that the fix ?

**Comment by Darkyenus** [comment]
@swolfekabaminc This repo is woefully out of date, my fix consists of rewriting and updating the template so that it works again with latest versions of libGDX, iOS and Android plugin.

**Comment by swolfekabaminc** [comment]
Ok, good to know. I saw that there had been a number of forks and was
interested myself in learning how to update the code. I'll make sure to
keep up to date with your repo.

**Comment by GiGurra** [comment]
Thanks Darkyenus for pointing us to your repo. Nice work :+1: 
Will be using this to trying libgdx
