### ISSUE TITLE
Cannot run with gdx-bullet dependency

### ISSUE THREAD

**Issue by ploddi** [ajhager/libgdx-sbt-project.g8#97]
```
[info] Loading global plugins from /Users/ploddi/.sbt/0.13/plugins
[info] Loading project definition from /Users/ploddi/Projects/hello-libgdx/project
[info] Set current project to all-platforms (in build file:/Users/ploddi/Projects/hello-libgdx/)
> last desktop/compile:run
[info] Running com.game.Main
[debug] Waiting for threads to exit or System.exit to be called.
[debug]   Classpath:
[debug]     /Users/ploddi/Projects/hello-libgdx/desktop/target/scala-2.11/desktop_2.11-0.1.jar
[debug]     /Users/ploddi/Projects/hello-libgdx/core/target/scala-2.11/core_2.11-0.1.jar
[debug]     /Users/ploddi/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.5.jar
[debug]     /Users/ploddi/.ivy2/cache/com.badlogicgames.gdx/gdx-backend-lwjgl/jars/gdx-backend-lwjgl-1.5.2.jar
[debug]     /Users/ploddi/.ivy2/cache/org.lwjgl.lwjgl/lwjgl/jars/lwjgl-2.9.2.jar
[debug]     /Users/ploddi/.ivy2/cache/org.lwjgl.lwjgl/lwjgl-platform/jars/lwjgl-platform-2.9.2-natives-osx.jar
[debug]     /Users/ploddi/.ivy2/cache/org.lwjgl.lwjgl/lwjgl-platform/jars/lwjgl-platform-2.9.2-natives-windows.jar
[debug]     /Users/ploddi/.ivy2/cache/org.lwjgl.lwjgl/lwjgl-platform/jars/lwjgl-platform-2.9.2-natives-linux.jar
[debug]     /Users/ploddi/.ivy2/cache/net.java.jinput/jinput/jars/jinput-2.0.5.jar
[debug]     /Users/ploddi/.ivy2/cache/net.java.jutils/jutils/jars/jutils-1.0.0.jar
[debug]     /Users/ploddi/.ivy2/cache/org.lwjgl.lwjgl/lwjgl_util/jars/lwjgl_util-2.9.2.jar
[debug]     /Users/ploddi/.ivy2/cache/com.badlogicgames.jlayer/jlayer/jars/jlayer-1.0.1-gdx.jar
[debug]     /Users/ploddi/.ivy2/cache/org.jcraft/jorbis/jars/jorbis-0.0.17.jar
[debug]     /Users/ploddi/.ivy2/cache/net.java.jinput/jinput-platform/jars/jinput-platform-2.0.5-natives-linux.jar
[debug]     /Users/ploddi/.ivy2/cache/net.java.jinput/jinput-platform/jars/jinput-platform-2.0.5-natives-osx.jar
[debug]     /Users/ploddi/.ivy2/cache/net.java.jinput/jinput-platform/jars/jinput-platform-2.0.5-natives-windows.jar
[debug]     /Users/ploddi/.ivy2/cache/com.badlogicgames.gdx/gdx-platform/jars/gdx-platform-1.5.2-natives-desktop.jar
[debug]     /Users/ploddi/.ivy2/cache/com.badlogicgames.gdx/gdx-bullet/jars/gdx-bullet-1.5.4.jar
[debug]     /Users/ploddi/.ivy2/cache/com.badlogicgames.gdx/gdx/jars/gdx-1.5.4.jar
[debug]     /Users/ploddi/.ivy2/cache/com.badlogicgames.gdx/gdx-bullet-platform/jars/gdx-bullet-platform-1.5.4-natives-desktop.jar
[debug] Waiting for thread run-main-0 to terminate.
[error] (run-main-0) java.lang.UnsatisfiedLinkError: com.badlogic.gdx.physics.bullet.collision.CollisionJNI.swig_module_init()V
java.lang.UnsatisfiedLinkError: com.badlogic.gdx.physics.bullet.collision.CollisionJNI.swig_module_init()V
    at com.badlogic.gdx.physics.bullet.collision.CollisionJNI.swig_module_init(Native Method)
    at com.badlogic.gdx.physics.bullet.collision.CollisionJNI.<clinit>(CollisionJNI.java:3202)
    at com.badlogic.gdx.physics.bullet.collision.btCollisionObject.<init>(btCollisionObject.java:221)
    at com.game.Main$.delayedEndpoint$com$game$Main$1(Main.scala:14)
    at com.game.Main$delayedInit$body.apply(Main.scala:6)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
    at scala.App$class.main(App.scala:76)
    at com.game.Main$.main(Main.scala:6)
    at com.game.Main.main(Main.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at sbt.Run.invokeMain(Run.scala:67)
    at sbt.Run.run0(Run.scala:61)
    at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
    at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
    at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
    at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
    at sbt.Logger$$anon$4.apply(Logger.scala:85)
    at sbt.TrapExit$App.run(TrapExit.scala:248)
    at java.lang.Thread.run(Thread.java:745)
[debug]     Thread run-main-0 exited.
[debug] Waiting for thread LWJGL Application to terminate.
```

**Comment by ploddi** [comment]
Dependency added as

```
  lazy val desktop = core ++ Seq(
    libraryDependencies ++= Seq(
      "net.sf.proguard" % "proguard-base" % "5.1" % "provided",
      "com.badlogicgames.gdx" % "gdx-backend-lwjgl" % libgdxVersion.value,
      "com.badlogicgames.gdx" % "gdx-platform" % libgdxVersion.value classifier "natives-desktop",
      "com.badlogicgames.gdx" % "gdx-bullet" % "1.5.4",
      "com.badlogicgames.gdx" % "gdx-bullet-platform" % "1.5.4" classifier "natives-desktop"
    ),
...
```

Mac OS X 10.10.2

**Comment by ploddi** [comment]
Possible issue: https://github.com/sbt/sbt/issues/358

**Comment by ploddi** [comment]
Actually not related to sbt. Bullet initiazation was incorrect. Close this.

**Comment by aginiewicz** [comment]
Glad you got it working!
